Added article and solution for GenerateParantheses
DivyaGodayal/CoderChef-Kitchen pull request #99
Opened 2019-01-16 23:23 UTC by Arihant1467

Added Article and Solution for [Genrate Parantheses](https://leetcode.com/problems/generate-parentheses/)

2019-01-19 02:24 UTC, edorado93 requested changes

2019-01-19 02:24 UTC, edorado93 commented on Backtracking/GenerateParantheses/README.md
> +So we are given `N` pairs of parentheses and return all the valid expressions. The above picture has all valid expressions for `n=3`.
1. Maybe rephrase the first sentence as `So we are given N pairs of parentheses and we want to return all the valid expressions possible by using those parentheses`.

2. The picture `below`

2019-01-19 02:24 UTC, edorado93 commented on Backtracking/GenerateParantheses/README.md
> +` (((( `
I think you want each expression on a new line.  Instead of using a single  `  here, use  ```  for a code block and put each expression on a single line.

2019-01-19 02:24 UTC, edorado93 commented on Backtracking/GenerateParantheses/README.md
> +After a careful observation of the tree and the expressions, all these expressions can be formed by making a <b>Postorder Traversal</b> of the tree. Out of these expressions we only add the valid one
`After careful observation of the tree, we can see that all these expressions ...`

2019-01-19 02:24 UTC, edorado93 commented on Backtracking/GenerateParantheses/README.md
> +<img align="center" alt="Question Screenshot" src="./../../Backtracking/GenerateParantheses/complete-recursion-tree.png">>
If it's not too much of a hassle, can you redraw the figure using round brackets rather than curly?

2019-01-19 02:24 UTC, edorado93 commented on Backtracking/GenerateParantheses/README.md
> +1. We start with an empty string  and mark it as `level=0`.
leave spaces between expressions e.g.

`level = 0`

2019-01-19 02:24 UTC, edorado93 commented on Backtracking/GenerateParantheses/README.md
> +3. At `level=n*2` we check if the formed expression is a valid one. If its valid then we add it otherwise we discard it.
This operation takes `O(N)` time as well. So the time complexity of your solution is actually `O(N * 2^N - 1)`. There's a better way of doing this, you don't need to check validity in the end. 

Essentially, you keep a track of a `left_parentheses_count` and `right_parentheses_count` and an index. The base condition is when `index` reaches `N`. As you mentioned, at every index you have two choices. You can either add a left parentheses and in the next recursive call pass `left_parentheses_count + 1`. 

For adding the right parentheses, you need to check first `right_parentheses_count < left_parentheses_count` because if this is not the case, then you would get an invalid string. So, only  if this condition is satisfied, you recurse further with `right_parentheses_count + 1`. When index reaches N, you simply check if `left_parentheses_count == right_parentheses_count`. Then the approach becomes `O(2^N)`. 

I'd recommend, you modify the existing approach and add this information in the algorithm itself.

2019-01-19 02:24 UTC, edorado93 commented on Backtracking/GenerateParantheses/solution.py
> +    def checker(self,expression):
As mentioned in my comment before, you can get rid of this and solve it in `O(1)` time by using two counters.

2019-01-19 02:24 UTC, edorado93 commented on Backtracking/GenerateParantheses/README.md
> +* Time Complexity: `O(2^n-1)` where n is the number of pairs of parantheses.
You need to add the space complexity as well.

2019-01-19 02:24 UTC, edorado93 commented on Backtracking/GenerateParantheses/README.md
> +#### Complexity Analysis
Can you please capitalize N?

2019-01-19 02:24 UTC, edorado93 commented on Backtracking/GenerateParantheses/README.md
> +<img align="center" alt="Question Screenshot" src="./../../Backtracking/GenerateParantheses/complete-recursion-tree.png">>
Also, in your diagram, can you write the final expressions along with the leaf nodes and maybe highlight the valid ones?

2019-01-19 02:24 UTC, edorado93 commented on README.md
> +  <tr>
We have all our backtracking problems in the `Adhoc` section for now, Can you move yours there as well. In there future, we will have a separate section for `Recursion and Backtracking`. For now just move it there.

2019-01-19 02:25 UTC, edorado93 commented
Hey, @Arihant1467 lemme know once you're done addressing the `review` related changes. I'll verify things once more and proceed with merging. Thanks for the article!

2019-01-22 10:22 UTC, Arihant1467 commented
Hi, @edorado93  I have made the requested changes. Let me know if any errors are there.

2019-01-22 22:46 UTC, edorado93 commented
Hey @Arihant1467, the changes look good to me. I made some minor changes to the README. Also, I moved the images to the respective folder in the `Images` directory. Rest looks good to me. Good job with the diagrams! Welcome to the kitchen 🍩 

![template_image_3](https://user-images.githubusercontent.com/11422365/51570684-893be200-1e54-11e9-8590-869c73d1d1b0.gif)

2019-01-22 22:47 UTC, merged